spring:
  application:
    name: conchclub


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
    
server:
  port: 8080

  error:
    include-message: always
    include-stacktrace: always

# Default configuration (can be overridden in application-local.yml)
jwt:
  secret: ${JWT_SECRET:}
  expiration:
    ms: ${JWT_EXPIRATION_MS:86400000}

tmdb:
  api:
    key: ${TMDB_API_KEY:}

user:
  registration:
    invite-code: ${INVITE_CODE:}
