spring:
  application:
    name: conchclub
  config:
    import: optional:classpath:application-local.yml
  datasource:
    url: jdbc:h2:mem:conchclubdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true

server:
  port: 8080

  error:
    include-message: always
    include-stacktrace: always

# Default configuration (can be overridden in application-local.yml)
jwt:
  secret: change_this_secret_to_something_very_long_and_secure_for_production_use_only
  expiration:
    ms: 86400000

google:
  credentials:
    path: ${GOOGLE_CREDENTIALS_PATH:credentials.json}  
